### PR TITLE
Fix typos in scip.proto

### PR DESCRIPTION
**Pull request by strager**

### CODE REVIEW

**Review by varungandhi-src — APPROVED** [review]

**Comment by varungandhi-src** [comment]
Thanks for the PR. The bindings will need to be regenerated, as the doc comments will be updated based on changes to the schema file. I can't push to this PR since it's from a fork, would you like me to create a separate PR or can you regenerate the bindings and push the change?

**Comment by strager** [comment]
I updated the bindings files.

**Comment by tjdevries** [comment]
(oh, hey strager!) not sure why it's generating a diff after the update. Maybe different version of one of the tools. I can try and check later if needed.

**Comment by varungandhi-src** [comment]
Closing this since there was a merge conflict again, I've fixed it in https://github.com/sourcegraph/scip/pull/194

**Pull request closed without merging**
